# Project properties
group = dev.nukecraft5419
name = ExamplePlugin
main = dev.nukecraft5419.exampleplugin.ExamplePlugin
version = 1.0.0
description = An example plugin
author = Nukecraft5419
apiVersion = 1.21

# Gradle properties
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC -Dfile.encoding=UTF-8
