#╔═══════════════════╗
#║ ● ExamplePlugin ● ║
#╚═══════════════════╝
fallback-language: "en_US"

#╔══════════════════╗
#║ ● Join Message ● ║
#╚══════════════════╝
join:
  enabled: true

#╔═════════════════════════╗
#║ ● Server Info Message ● ║
#╚═════════════════════════╝
server-info:
  enabled: true
