name: "${name}"
main: "${main}"
version: "${version}"
description: "${description}"
author: "${author}"
api-version: "${apiVersion}"
softdepend: [PlaceholderAPI]
commands:
    exampleplugin:
        description: Main command for the plugin
        aliases: example
    hello:
        description: Say hi
        aliases: hi
